version: '2'
services:
  apache:
    image: khuenqdev/magento191:latest
    ports:
      - "80:80" # web
      - "9001:9000" # xdebug
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/apache2
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - <project_name>-network

  db:
    image: mariadb:10.4
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - <project_name>-network

networks:
  <project_name>-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

